# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def fib_even_sum(n)
  fib_arr = [1, 1]
  sum = 0

  until fib_arr[-1] >= n
    fib_arr << (fib_arr[-2] + fib_arr[-1])
    sum += fib_arr[-2] if fib_arr[-2].even?
  end

  sum
end

p fib_even_sum(4000000)
